name: CI/CD pour Atelier 1 
# Controle de la chaine CI/CD
on:
  push:
    branches: [atl1_test]
# Les taches (jobs) à effectuer
jobs:
  # Chaque tache est représentée par un serveur, ce qui permet l'indépendance des tâches.
  build-test: # Tache pour build et test
    runs-on: ubuntu-latest # Choix de l'OS du serveur pour l'étape 'build-test'
    steps:
      - uses: actions/checkout@v2 # Ne pas toucher
      - name: "[CI] Initialiser l'environnement Python"
        run: cd atelier/ && ./init.sh
      - name: "[CI] Démarrer le serveur Python"
        run: cd atelier/ && ./run.sh
      - name: "[CI] Tester le serveur Python"
        run: curl http://localhost:8000/
  deploy: # Tache pour deploiement
    runs-on: ubuntu-latest # Choix de l'OS du serveur pour l'étape 'build-test'
    needs: build-test # Indique que ce job démarre uniquement si le job 'build-test' est un succès
    steps:
      - uses: actions/checkout@v2 # Ne pas toucher
      - name: "[CD] Publication du code"
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }} #Deta access token https://docs.deta.sh/docs/cli/auth
          deta-name: 'atelier' #Deta Micro name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project: 'default' 
          deta-project-dir: 'atelier/'
